import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Copy, Heart, Play } from 'lucide-react';
export const PromptCard = ({ prompt, onCopy, onToggleFav, onInject }) => {
    const toolColors = {
        'ChatGPT': 'bg-green-100 text-green-800 border-green-800',
        'Midjourney': 'bg-purple-100 text-purple-800 border-purple-800',
        'Claude': 'bg-orange-100 text-orange-800 border-orange-800',
        'Gemini': 'bg-blue-100 text-blue-800 border-blue-800',
        'Stable Diffusion': 'bg-indigo-100 text-indigo-800 border-indigo-800',
    };
    return (_jsx("div", { className: "break-inside-avoid mb-6 group", children: _jsxs("div", { className: "bg-white border-2 border-brand-black rounded-xl overflow-hidden transition-all duration-200 hover:-translate-y-1 hover:shadow-neo", children: [_jsxs("div", { className: "p-4 pb-0 flex justify-between items-start", children: [_jsx("span", { className: `text-[10px] font-black px-2 py-0.5 rounded border uppercase tracking-wider ${toolColors[prompt.tool] || 'bg-gray-100'}`, children: prompt.tool }), _jsx("button", { onClick: () => onToggleFav(prompt.id), className: "text-slate-300 hover:text-red-500 transition-colors active:scale-90", title: prompt.isFavorite ? "Remove from favorites" : "Add to favorites", children: _jsx(Heart, { size: 20, className: prompt.isFavorite ? 'fill-red-500 text-red-500' : 'fill-transparent', strokeWidth: 2.5 }) })] }), _jsxs("div", { className: "p-4", children: [_jsx("h3", { className: "font-display text-lg font-bold leading-tight mb-2 text-brand-black", children: prompt.title }), _jsx("p", { className: "text-xs text-slate-500 font-medium line-clamp-2 mb-3", children: prompt.description }), _jsxs("div", { onClick: () => onCopy(prompt.content), className: "relative group/code bg-brand-gray border-2 border-slate-200 rounded-lg p-3 cursor-pointer hover:border-brand-black transition-colors", children: [_jsx("code", { className: "block font-mono text-xs text-slate-700 line-clamp-4 leading-relaxed selection:bg-brand-yellow", children: prompt.content }), _jsx("div", { className: "absolute top-2 right-2 opacity-0 group-hover/code:opacity-100 transition-opacity bg-brand-black text-white p-1 rounded shadow-sm", children: _jsx(Copy, { size: 12 }) })] }), _jsx("div", { className: "flex flex-wrap gap-1 mt-3", children: prompt.tags.map(tag => (_jsxs("span", { className: "text-[10px] font-bold text-slate-400", children: ["#", tag] }, tag))) })] }), _jsxs("div", { className: "border-t-2 border-brand-black p-2 bg-brand-gray flex gap-2", children: [_jsxs("button", { onClick: () => onInject(prompt.content), className: "flex-1 bg-brand-black text-white text-xs font-bold py-2 rounded-lg flex items-center justify-center gap-2 hover:bg-slate-800 active:translate-y-0.5 transition-all", children: [_jsx(Play, { size: 12, className: "fill-current" }), "Magic Fill"] }), _jsx("button", { onClick: () => onCopy(prompt.content), className: "px-3 py-2 bg-white border-2 border-brand-black rounded-lg text-brand-black hover:bg-brand-yellow active:translate-y-0.5 transition-all", "aria-label": "Copy to clipboard", children: _jsx(Copy, { size: 14, strokeWidth: 2.5 }) })] })] }) }));
};
